Add missing Boost.Filesystem header to mainscreen.C
This file uses `fs::directory_iterator` so it needs the relevant header.  This causes a build failure with Boost 1.90.0:

```
src/mainscreen.C: In member function ‘void BTMainScreen::run()’:
src/mainscreen.C:43:6: error: ‘directory_iterator’ is not a member of ‘fs’; did you mean ‘directory_entry’?
   43 |  fs::directory_iterator end_iter;
      |      ^~~~~~~~~~~~~~~~~~
      |      directory_entry
```